[package]
name = "rust_crash_course"
version = "0.1.0"
authors = ["Samuel Ibarra <ing.samuelibarra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
